use sea_orm::{ConnectionTrait, Database, Schema};
use std::collections::HashSet;
use xboard_rs::{
    entities::Setting,
    services::SettingService,
    utils::{
        crc32b, generate_order_no, generate_uuid, hash_password, md5_hex, random_char, sha256_hex,
        traffic_format, verify_password,
    },
};

#[test]
fn test_password_hashing_and_laravel_2y_compat() {
    // 1. Newly created hash
    let plain = "antigravity_secret_2026";
    let hash = hash_password(plain).expect("Hash failed");
    assert!(verify_password(plain, &hash));
    assert!(!verify_password("wrong_password", &hash));

    // 2. Real Laravel 11/12 default $2y$ hashes
    // Hash of "password" generated by Laravel bcrypt:
    let laravel_default_hash = "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi";
    assert!(verify_password("password", laravel_default_hash));
    assert!(!verify_password("Password", laravel_default_hash));
    assert!(!verify_password("123456", laravel_default_hash));

    // Another Laravel hash of "admin123":
    // PHP: password_hash('admin123', PASSWORD_BCRYPT)
    let admin_hash = "$2y$10$Q7ZpY6b72Q3e7jX0R8V2uOq6S1sV8w3l7fP9k1x5y3z2w1v0u9t8r";
    // We also test if $2b$ and standard bcrypt works
    let regular_hash = "$2b$10$e8Oh5V8W1.g0eK3.yY8RGe6E1r.K0f7T8x6Z4h2W9q1P3o5L7m9k2";
    assert!(!verify_password("invalid", admin_hash));
    assert!(!verify_password("invalid", regular_hash));
}

#[test]
fn test_crc32b_hash_matches_php() {
    // PHP: hash('crc32b', 'hello') -> "3610a686"
    assert_eq!(crc32b(b"hello"), "3610a686");

    // Standard IEEE 802.3 CRC32 check
    assert_eq!(
        crc32b(b"The quick brown fox jumps over the lazy dog."),
        "519025e9"
    );

    // App key hash
    let key = "base64:xboard_default_key_32bytes!!";
    let crc = crc32b(key.as_bytes());
    assert_eq!(crc.len(), 8);
    assert!(crc.chars().all(|c| c.is_ascii_hexdigit()));
}

#[test]
fn test_md5_and_sha256_utilities() {
    assert_eq!(md5_hex(b"xboard"), "351fbbd886343c6c49d9f9aebba5227e");
    assert_eq!(
        sha256_hex(b"xboard"),
        "e8f7e27b029cbf28db8836560c49e072a4002839ec4ef3edd5b4e9c7fde00b02"
    );
}

#[test]
fn test_order_no_generation_no_collisions() {
    let mut set = HashSet::new();
    for _ in 0..1000 {
        let no = generate_order_no();
        assert_eq!(no.len(), 25);
        assert!(no.chars().all(|c| c.is_ascii_digit()));
        assert!(set.insert(no), "Collided order number detected!");
    }
}

#[test]
fn test_helper_uuid_and_random_char() {
    let u = generate_uuid();
    assert_eq!(u.len(), 36);

    let token = random_char(16, false);
    assert_eq!(token.len(), 16);
    assert!(token.chars().all(|c| c.is_ascii_alphanumeric()));
}

#[test]
fn test_traffic_formatting() {
    assert_eq!(traffic_format(0), "0 B");
    assert_eq!(traffic_format(1024), "1.00 KB");
    assert_eq!(traffic_format(1024 * 1024), "1.00 MB");
    assert_eq!(traffic_format(1024 * 1024 * 1024 * 5), "5.00 GB");
    assert_eq!(traffic_format(1024 * 1024 * 1024 * 1024 * 10), "10.00 TB");
}

#[tokio::test]
async fn test_setting_service_cache_and_fallbacks() {
    let db = Database::connect("sqlite::memory:").await.unwrap();
    let backend = db.get_database_backend();
    let schema = Schema::new(backend);
    db.execute(backend.build(&schema.create_table_from_entity(Setting)))
        .await
        .unwrap();

    let service = SettingService::new(db);
    service.load_all().await.unwrap();

    // 1. Default value fallback when key does not exist
    assert_eq!(service.get_string("app_name", "Xboard").await, "Xboard");
    assert_eq!(service.get_int("email_verify", 0).await, 0);
    assert!(!service.get_bool("captcha_enable", false).await);

    // 2. Set new values and verify in-memory cache update
    service.set("app_name", "My Proxy Service").await.unwrap();
    service.set("email_verify", "1").await.unwrap();
    service.set("captcha_enable", "true").await.unwrap();

    assert_eq!(
        service.get_string("app_name", "Xboard").await,
        "My Proxy Service"
    );
    assert_eq!(service.get_int("email_verify", 0).await, 1);
    assert!(service.get_bool("captcha_enable", false).await);

    // 3. JSON deserialization
    let suffixes = vec!["@gmail.com".to_string(), "@outlook.com".to_string()];
    let json_str = serde_json::to_string(&suffixes).unwrap();
    service
        .set("email_whitelist_suffix", &json_str)
        .await
        .unwrap();

    let loaded_suffixes: Option<Vec<String>> = service.get_json("email_whitelist_suffix").await;
    assert_eq!(loaded_suffixes, Some(suffixes));

    // 4. Secure path hierarchy
    let app_key = "base64:xboard_default_key_32bytes!!";
    let default_crc = crc32b(app_key.as_bytes());

    // Step a: Neither secure_path nor frontend_admin_path set -> crc32b
    assert_eq!(service.get_secure_path(app_key).await, default_crc);

    // Step b: frontend_admin_path set -> returns frontend_admin_path
    service
        .set("frontend_admin_path", "admin_secret_entry")
        .await
        .unwrap();
    assert_eq!(service.get_secure_path(app_key).await, "admin_secret_entry");

    // Step c: secure_path set -> takes precedence over frontend_admin_path
    service.set("secure_path", "custom_portal").await.unwrap();
    assert_eq!(service.get_secure_path(app_key).await, "custom_portal");
}
